// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { getSupabaseEnv } from '@/lib/env';

// Safely initialize Supabase client
// If env vars are missing, we provide placeholders to prevent compile/runtime crash on import,
// but the app will be broken (which we detect in UI via checkSupabaseEnv)
let supabaseUrl = '';
let supabaseAnonKey = '';

try {
  const env = getSupabaseEnv();
  supabaseUrl = env.url;
  supabaseAnonKey = env.anonKey;
} catch (error) {
  console.error('Supabase initialization error:', error);
  // Fallback to avoid crash on import
  supabaseUrl = 'https://placeholder.supabase.co';
  supabaseAnonKey = 'placeholder';
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

